/**
 * JSON Schema (draft-07) for graph.json. Kept in lockstep with types.ts.
 * `additionalProperties: false` everywhere so drift / typos fail fast (SCHEMA-01).
 */
export const graphFileSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'https://arch-viz.local/graph.schema.json',
  title: 'GraphFile',
  type: 'object',
  additionalProperties: false,
  required: ['meta', 'nodes', 'edges', 'clusters'],
  properties: {
    meta: { $ref: '#/definitions/meta' },
    nodes: { type: 'array', items: { $ref: '#/definitions/node' } },
    edges: { type: 'array', items: { $ref: '#/definitions/edge' } },
    clusters: { type: 'array', items: { $ref: '#/definitions/cluster' } },
  },
  definitions: {
    meta: {
      type: 'object',
      additionalProperties: false,
      required: [
        'schemaVersion',
        'generatedAt',
        'sourceRepo',
        'sourceRepoHash',
        'generator',
        'counts',
        'layout',
        'clustering',
      ],
      properties: {
        schemaVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
        generatedAt: { type: 'string', format: 'date-time' },
        sourceRepo: { type: 'string' },
        sourceRepoHash: { type: 'string' },
        generator: {
          type: 'object',
          additionalProperties: false,
          required: [
            'name',
            'version',
            'engine',
            'engineVersion',
            'codegraphSchema',
            'codegraphDbHash',
          ],
          properties: {
            name: { type: 'string' },
            version: { type: 'string' },
            engine: { type: 'string' },
            engineVersion: { type: 'string' },
            codegraphSchema: { type: 'integer' },
            codegraphDbHash: { type: 'string' },
          },
        },
        counts: {
          type: 'object',
          additionalProperties: false,
          required: ['nodes', 'edges', 'clusters'],
          properties: {
            nodes: { type: 'integer', minimum: 0 },
            edges: { type: 'integer', minimum: 0 },
            clusters: { type: 'integer', minimum: 0 },
          },
        },
        layout: {
          type: 'object',
          additionalProperties: false,
          required: ['algo', 'rankdir', 'version'],
          properties: {
            algo: { type: 'string', enum: ['dagre'] },
            rankdir: { type: 'string', enum: ['LR', 'TB', 'RL', 'BT'] },
            version: { type: 'integer' },
          },
        },
        clustering: {
          type: 'object',
          additionalProperties: false,
          required: ['algo', 'seed', 'resolution'],
          properties: {
            algo: { type: 'string', enum: ['louvain'] },
            seed: { type: 'integer' },
            resolution: { type: 'number' },
          },
        },
      },
    },
    node: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'kind',
        'label',
        'qualifiedName',
        'path',
        'lang',
        'span',
        'cluster',
        'flags',
        'metrics',
        'position',
        'annotations',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        kind: { type: 'string', enum: ['module', 'file', 'class', 'function'] },
        label: { type: 'string' },
        qualifiedName: { type: 'string' },
        path: { type: 'string' },
        lang: { type: 'string' },
        span: {
          type: 'object',
          additionalProperties: false,
          required: ['startLine', 'endLine'],
          properties: {
            startLine: { type: 'integer' },
            endLine: { type: 'integer' },
          },
        },
        cluster: { type: 'integer', minimum: -1 },
        flags: {
          type: 'object',
          additionalProperties: false,
          required: ['exported', 'async', 'static', 'abstract'],
          properties: {
            exported: { type: 'boolean' },
            async: { type: 'boolean' },
            static: { type: 'boolean' },
            abstract: { type: 'boolean' },
          },
        },
        metrics: {
          type: 'object',
          additionalProperties: false,
          required: ['loc', 'fanIn', 'fanOut', 'descendants'],
          properties: {
            loc: { type: 'integer', minimum: 0 },
            fanIn: { type: 'integer', minimum: 0 },
            fanOut: { type: 'integer', minimum: 0 },
            descendants: { type: 'integer', minimum: 0 },
          },
        },
        position: {
          type: 'object',
          additionalProperties: false,
          required: ['x', 'y'],
          properties: {
            x: { type: 'number' },
            y: { type: 'number' },
          },
        },
        annotations: { type: ['string', 'null'] },
      },
    },
    edge: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'source', 'target', 'kind', 'weight', 'confidence', 'resolvedBy'],
      properties: {
        id: { type: 'string', minLength: 1 },
        source: { type: 'string', minLength: 1 },
        target: { type: 'string', minLength: 1 },
        kind: { type: 'string', enum: ['imports', 'calls', 'contains'] },
        weight: { type: 'integer', minimum: 1 },
        confidence: { type: 'number', minimum: 0, maximum: 1 },
        resolvedBy: { type: 'string' },
      },
    },
    cluster: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'label', 'color', 'nodeIds', 'size', 'annotations'],
      properties: {
        id: { type: 'integer', minimum: 0 },
        label: { type: 'string' },
        color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' },
        nodeIds: { type: 'array', items: { type: 'string' } },
        size: { type: 'integer', minimum: 0 },
        annotations: { type: ['string', 'null'] },
      },
    },
  },
};
